# Generated by Django 4.1.1 on 2022-10-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, null=True)),
                ('last_name', models.CharField(max_length=15, null=True)),
                ('admission_number', models.CharField(max_length=10, null=True)),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upeoapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Revision_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('message', models.CharField(max_length=20)),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upeoapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=6, null=True)),
                ('message', models.CharField(max_length=15, null=True)),
                ('date', models.DateTimeField()),
                ('origin', models.CharField(max_length=6, null=True)),
                ('title', models.CharField(max_length=15, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upeoapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('message', models.CharField(max_length=10)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upeoapp.student')),
            ],
        ),
    ]
