# Generated by Django 4.1.1 on 2022-10-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upeoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='corect_answer',
            new_name='correct_answer',
        ),
    ]
