# Generated by Django 4.1.1 on 2022-10-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upeoapp', '0002_alter_topic_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='title',
        ),
        migrations.AddField(
            model_name='questions',
            name='question',
            field=models.TextField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answers',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
