# Generated by Django 4.1.1 on 2022-10-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upeoapp', '0003_remove_questions_title_questions_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='title',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='title',
        ),
        migrations.RemoveField(
            model_name='student',
            name='admission_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AddField(
            model_name='answers',
            name='corect_answer',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
