# Generated by Django 4.1.1 on 2022-10-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upeoapp', '0004_button_alter_notification_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='confirmpassword',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
