# Generated by Django 4.1.1 on 2022-10-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upeoapp', '0004_rename_title_topic_topic_remove_answers_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=40),
        ),
    ]
