# Generated by Django 4.1.1 on 2022-10-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upeoapp', '0006_alter_signup_first_name_alter_signup_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='confirm_password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
